# fly.toml app configuration file generated for snap-text-backend on 2025-03-26T10:45:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


app = 'snap-text-backend'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3008
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
